{% set name = "hydrotoolbox" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydrotoolbox-{{ version }}.tar.gz
  sha256: 5f9129f89c0215e9b1f60d5051aaf0c95cc902eafe29e157f7be2511f5b81898

build:
  entry_points:
    - hydrotoolbox = hydrotoolbox.hydrotoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - cltoolbox >=1.0.0
    - toolbox_utils >=3.0.0,<4.0.0
    - pydantic

test:
  imports:
    - hydrotoolbox
  commands:
    - pip check
    - hydrotoolbox --help
  requires:
    - pip

about:
  summary: Command line script and Python library for analysis of flow time-series.
  home: https://pypi.org/project/hydrotoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
