{% set name = "hydrotoolbox" %}
{% set version = "2.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydrotoolbox-{{ version }}.tar.gz
  sha256: ab2451073aef05d761ef70681d2d7b2072a946e6d9b0624ee18ba69e2d20e299

build:
  entry_points:
    - hydrotoolbox = hydrotoolbox.hydrotoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cltoolbox >=1.0.0
    - pydantic
    - dateparser
    - numpy >=1.20
    - numpy <2.0
    - pandas
    - pint !=0.21
    - pint-pandas
    - pydantic
    - scipy
    - tabulate

test:
  imports:
    - hydrotoolbox
  commands:
    - pip check
    - hydrotoolbox --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Command line script and Python library for analysis of flow time-series.
  home: https://pypi.org/project/hydrotoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
